// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzbncmlposznelfnobcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6Ym5jbWxwb3N6bmVsZm5vYmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDA3NDUsImV4cCI6MjA2MTExNjc0NX0.7aKHJJfHP9rx853fX0kNFvGeDAklElPEEr2Nh8TaiR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);